### ISSUE TITLE
Add live demo

### ISSUE THREAD

**Issue by E-fais** [Sofiya-Mathew/Shopping-Cart-Using_JS#1]
You can host your website from github for free,
Go to settings—> pages—> deploy from branch.
Select your branch , here you have only one branch so select it and click save.
It will take a few minutes, refresh the page and yiu can see the url for your website.

**Comment by Sofiya-Mathew** [comment]
Hey .. i have added the live demo link in the post description.. do check
it out! Thank you!

**Comment by E-fais** [comment]
@Sofiya-Mathew athew , you can privide your link in about settings or try to include in README file. 
Creating a README file for your projects is important. Thanks.
you can provide a link as follows 
[live demo](https://sofiya-mathew.github.io/Shopping-Cart-Using_JS/)
If you need any help doing this please let me know.
